name: Update Quote Readme

on:
  push:
    branches:
      - main
      - master

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
